### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by atteson** [ManuelStapper/RandomVariables.jl#5]
Your project looks very interesting.  As it turns out, I just started a similar project in julia a few days ago.  I'm open to trying to combine our projects if you think that's useful or we can evolve them separately.  My fledgling project is atteson/RandomElements.jl though it doesn't yet have any documentation.  There are a few places that I'm doing things differently than you:

1.  The biggest difference is that I allow my equivalent of RVtransformed to be defined in terms of other RVtransformed.  Hence, one can do:

```
X = RV(Normal())
Y = RV(Normal())
Z = X + Y
```

The disadvantage of this is that such transformations are not invertible which makes some of the operations you're doing impossible.

2.  I've focused more on sampling than calculation of probabilities.  Hence, I can do ```rand([X,Y,Z])``` with X, Y and Z defined as above and they will be sampled in a consistent way.

3.  Rather than "random variables", I'm focusing on "random elements", which can be random variables, random vectors or arbitrary other random objects.  This generalization leads to a different focus (e.g. sampling rather than probability calculation since sampling is always possible).

Kevin Atteson

**Comment by ManuelStapper** [comment]
Thanks for your comment. I thought about adding a sampler function to the RVs earlier but it's not at the top of my agenda rn. Next steps will be conditional RVs and addition of RVs. The latter, as you mentioned, would need numerical integration and summation to compute probabilities - still in the phase of structuring it.
Anyway, I tried your package and came across something I struggled with earlier. If you run

```
X = IndependentRandomElement(Normal())
Y = IndependentRandomElement(Normal())
Z = X + Y
rand([X, Y, Z])
```

then the values sampled for X and Y are identical and I expected them not to be. Is that intended? Maybe it's connected to equal object IDs of X and Y (since distributions are immutable?). That was the reason I included an ID for the random variable type in my package.

We should definitely keep in touch, no matter if we decide to combine the packages or not.

**Comment by atteson** [comment]
Thanks for pointing out that bug!  The issue was that I had set up IndependentRandomElement as a struct and Normal is also a struct.  That means that X and Y in the above are exactly the same object.  I store the objects in a Dict so I know if I had already sampled a particular random element and X and Y ended up getting conflated.

I fixed it by making IndependentRandomElement a mutable struct which means each becomes a pointer to a struct so that the pointers for X and Y will be different.  I also added a test case for this bug into my test.  I left TransformedRandomElement as a struct so that:

```
X = IndependentRandomElement( Normal() )
Y = X + 1
Z = X + 1
rand( [Y,Z] )
```

should only do the calculation once.
